const keys = ['budget.title','budget.enabled','budget.period','budget.day','budget.month','budget.metric','budget.tokens','budget.cost','budget.currency','budget.threshold','budget.invalid','budget.pricingRequired','budget.hint','budget.current','budget.limited','budget.reached','export.details','import.preview','import.detailsDone'];
const phrases: Record<string, string[]> = {
  'zh-CN': ['预算提醒','启用提醒','周期','本地日','本地月','指标','已知总 token','发生时估算金额','币种','阈值','请输入正整数 token 或最多六位小数的正金额。','金额提醒需要启用费用估算。','仅在应用内提醒；重启和补录不会重复提醒同一周期阈值。','当前已知量：{amount} {unit}','覆盖受限，未知用量及未计价部分没有计入。','预算阈值已达到：{amount} / {threshold} {unit}','导出明细交换包','将导入 {sources} 个来源、{details} 条明细、{cumulative} 条累计、{daily} 个归档日分区，时区 {timezone}。确认继续？','明细新增 {added}、更新 {updated}、重复 {unchanged}、跳过 {skipped}、冲突 {conflicts}；累计变更 {cumulative}。'],
  'zh-TW': ['預算提醒','啟用提醒','週期','本地日','本地月','指標','已知總 token','發生時估算金額','幣別','閾值','請輸入正整數 token 或最多六位小數的正金額。','金額提醒需要啟用費用估算。','僅在應用內提醒；重啟和補錄不會重複提醒相同週期閾值。','目前已知量：{amount} {unit}','涵蓋受限，未知用量及未計價部分未計入。','預算閾值已達到：{amount} / {threshold} {unit}','匯出明細交換包','將匯入 {sources} 個來源、{details} 筆明細、{cumulative} 筆累計、{daily} 個封存日分區，時區 {timezone}。確認繼續？','明細新增 {added}、更新 {updated}、重複 {unchanged}、略過 {skipped}、衝突 {conflicts}；累計變更 {cumulative}。'],
  en: ['Budget reminders','Enable reminders','Period','Local day','Local month','Metric','Known total tokens','Estimated cost at time of use','Currency','Threshold','Enter positive whole tokens or a positive amount with up to six decimal places.','Cost reminders require cost estimation.','In-app reminders only; restarting or backfilling does not repeat the same period threshold.','Current known amount: {amount} {unit}','Coverage is limited; unknown usage and unpriced parts are excluded.','Budget threshold reached: {amount} / {threshold} {unit}','Export detail exchange','Import {sources} sources, {details} details, {cumulative} cumulative snapshots and {daily} archived daily partitions in {timezone}. Continue?','Details: {added} added, {updated} updated, {unchanged} repeated, {skipped} skipped, {conflicts} conflicts; {cumulative} cumulative changes.'],
  ja: ['予算通知','通知を有効にする','期間','ローカル日','ローカル月','指標','既知の総 token','使用時点の推定費用','通貨','しきい値','正の整数 token または小数点以下6桁までの正の金額を入力してください。','費用通知には費用推定が必要です。','アプリ内で通知します。再起動や過去データの追加で同じ期間の通知は繰り返しません。','現在の既知量：{amount} {unit}','範囲に制限があります。不明な用量と未計価部分は含みません。','予算しきい値に到達：{amount} / {threshold} {unit}','明細交換をエクスポート','{timezone} の {sources} ソース、{details} 明細、{cumulative} 累計、{daily} 保存日区分を読み込みます。続行しますか？','明細：追加 {added}、更新 {updated}、重複 {unchanged}、除外 {skipped}、競合 {conflicts}。累計変更 {cumulative}。'],
  ko: ['예산 알림','알림 사용','기간','현지 날짜','현지 월','지표','알려진 총 token','사용 시점의 추정 비용','통화','임계값','양의 정수 token 또는 소수점 이하 6자리까지의 양수를 입력하세요.','비용 알림에는 비용 추정이 필요합니다.','앱 안에서만 알립니다. 재시작이나 과거 데이터 추가로 같은 기간의 알림을 반복하지 않습니다.','현재 알려진 양: {amount} {unit}','범위가 제한됩니다. 알 수 없는 사용량과 가격이 없는 부분은 제외됩니다.','예산 임계값 도달: {amount} / {threshold} {unit}','상세 교환 내보내기','{timezone}의 소스 {sources}개, 상세 {details}개, 누적 {cumulative}개, 보관 날짜 {daily}개를 가져옵니다. 계속할까요?','상세: 추가 {added}, 갱신 {updated}, 중복 {unchanged}, 제외 {skipped}, 충돌 {conflicts}; 누적 변경 {cumulative}.'],
  es: ['Avisos de presupuesto','Activar avisos','Periodo','Día local','Mes local','Métrica','Tokens totales conocidos','Coste estimado al usar','Moneda','Umbral','Introduzca tokens enteros positivos o un importe positivo con hasta seis decimales.','Los avisos de coste requieren la estimación.','Avisos dentro de la aplicación; reiniciar o añadir datos históricos no repite el mismo aviso.','Importe conocido actual: {amount} {unit}','Cobertura limitada; se excluyen el uso desconocido y las partes sin precio.','Umbral alcanzado: {amount} / {threshold} {unit}','Exportar intercambio detallado','Importar {sources} fuentes, {details} detalles, {cumulative} acumulados y {daily} particiones diarias archivadas en {timezone}. ¿Continuar?','Detalles: {added} nuevos, {updated} actualizados, {unchanged} repetidos, {skipped} omitidos, {conflicts} conflictos; {cumulative} cambios acumulados.'],
  fr: ['Alertes de budget','Activer les alertes','Période','Jour local','Mois local','Indicateur','Total de tokens connus','Coût estimé au moment de l’usage','Devise','Seuil','Saisissez des tokens entiers positifs ou un montant positif avec au plus six décimales.','Les alertes de coût nécessitent l’estimation des coûts.','Alertes dans l’application ; un redémarrage ou un ajout historique ne répète pas le même seuil.','Montant connu actuel : {amount} {unit}','Couverture limitée ; l’usage inconnu et les éléments sans prix sont exclus.','Seuil atteint : {amount} / {threshold} {unit}','Exporter les détails','Importer {sources} sources, {details} détails, {cumulative} cumuls et {daily} partitions journalières archivées dans {timezone}. Continuer ?','Détails : {added} ajouts, {updated} mises à jour, {unchanged} doublons, {skipped} exclusions, {conflicts} conflits ; {cumulative} changements cumulés.'],
  de: ['Budgethinweise','Hinweise aktivieren','Zeitraum','Lokaler Tag','Lokaler Monat','Messwert','Bekannte Gesamttokens','Geschätzte Kosten bei Nutzung','Währung','Schwelle','Positive ganze Tokens oder einen positiven Betrag mit bis zu sechs Dezimalstellen eingeben.','Kostenhinweise erfordern die Kostenschätzung.','Hinweise in der App; Neustart und Nachträge wiederholen dieselbe Periodenschwelle nicht.','Aktueller bekannter Wert: {amount} {unit}','Abdeckung begrenzt; unbekannte Nutzung und unbepreiste Teile fehlen.','Budgetschwelle erreicht: {amount} / {threshold} {unit}','Detailaustausch exportieren','{sources} Quellen, {details} Details, {cumulative} Summen und {daily} archivierte Tagespartitionen in {timezone} importieren. Fortfahren?','Details: {added} neu, {updated} aktualisiert, {unchanged} wiederholt, {skipped} übersprungen, {conflicts} Konflikte; {cumulative} Summenänderungen.'],
  'pt-BR': ['Alertas de orçamento','Ativar alertas','Período','Dia local','Mês local','Métrica','Total de tokens conhecidos','Custo estimado no uso','Moeda','Limite','Insira tokens inteiros positivos ou um valor positivo com até seis casas decimais.','Alertas de custo exigem a estimativa de custos.','Alertas no aplicativo; reiniciar ou incluir histórico não repete o mesmo limite do período.','Valor conhecido atual: {amount} {unit}','Cobertura limitada; uso desconhecido e partes sem preço são excluídos.','Limite atingido: {amount} / {threshold} {unit}','Exportar intercâmbio detalhado','Importar {sources} fontes, {details} detalhes, {cumulative} acumulados e {daily} partições diárias arquivadas em {timezone}. Continuar?','Detalhes: {added} novos, {updated} atualizados, {unchanged} repetidos, {skipped} ignorados, {conflicts} conflitos; {cumulative} alterações acumuladas.'],
  ru: ['Уведомления о бюджете','Включить уведомления','Период','Местный день','Местный месяц','Показатель','Известное общее число токенов','Оценка стоимости на момент использования','Валюта','Порог','Введите положительное целое число токенов или сумму с точностью до шести знаков.','Для уведомлений о стоимости нужна оценка расходов.','Уведомления внутри приложения; перезапуск и добавление истории не повторяют тот же порог периода.','Текущее известное значение: {amount} {unit}','Охват ограничен; неизвестный расход и части без цены исключены.','Порог бюджета достигнут: {amount} / {threshold} {unit}','Экспортировать подробности','Импортировать источников: {sources}, записей: {details}, накопленных значений: {cumulative}, архивных дней: {daily}, часовой пояс: {timezone}. Продолжить?','Записи: добавлено {added}, обновлено {updated}, повторов {unchanged}, пропущено {skipped}, конфликтов {conflicts}; накопленных изменений {cumulative}.'],
};
export const completionCatalogs: Record<string, Record<string, string>> = Object.fromEntries(
  Object.entries(phrases).map(([locale, values]) => [locale, Object.fromEntries(keys.map((key, i) => [key, values[i]]))]),
);
const dismiss: Record<string,string> = {'zh-CN':'关闭提醒','zh-TW':'關閉提醒',en:'Dismiss',ja:'通知を閉じる',ko:'알림 닫기',es:'Cerrar aviso',fr:'Fermer',de:'Hinweis schließen','pt-BR':'Fechar alerta',ru:'Закрыть уведомление'};
for (const [locale,text] of Object.entries(dismiss)) completionCatalogs[locale]['budget.dismiss']=text;
