const keys=['dashboard.priceReference','cost.unitPrices','cost.unitPriceHint','cost.noUnitPrice','cost.cacheWrite5m','cost.cacheWrite1h','cost.contextTier','chart.totalMissing','cost.detailLimited','quota.details'];
const phrases:Record<string,string[]>={
  'zh-CN':['采用当前可用价目，分币种展示；仅为 API 参考。','查看模型单价','每百万 token；展示实际匹配价目及上下文档位，— 表示该项单价缺失。','暂无适用单价','缓存写入 · 5分钟','缓存写入 · 1小时','输入上下文 ≥ {count} token','完整总 token 未提供','部分历史明细已过期，参考金额仅覆盖仍保留的明细。','额度详情'],
  'zh-TW':['採用目前可用價目，分幣種顯示；僅供 API 參考。','查看模型單價','每百萬 token；顯示實際匹配價目與上下文級距，— 表示該項單價缺失。','暫無適用單價','快取寫入 · 5分鐘','快取寫入 · 1小時','輸入上下文 ≥ {count} token','未提供完整總 token','部分歷史明細已過期，參考金額僅涵蓋保留的明細。','額度詳情'],
  en:['Current available rates, per currency; API reference only.','View model unit prices','Per million tokens; matched rates and context tiers. — means no rate for this component.','No applicable unit price','Cache write · 5 min','Cache write · 1 hour','Input context ≥ {count} tokens','Complete total tokens not provided','Some historical details have expired; reference amounts cover retained details only.','Quota details'],
  ja:['現在利用できる料金を通貨別に表示。API の参考額です。','モデル単価を見る','100万 token あたり。実際に適用した料金とコンテキスト区分を表示。— は単価なし。','適用できる単価なし','キャッシュ書込 · 5分','キャッシュ書込 · 1時間','入力コンテキスト ≥ {count} token','完全な合計 token は未提供','過去の一部明細は期限切れです。参考額は保持された明細のみ対象です。','枠の詳細'],
  ko:['현재 사용 가능한 요금을 통화별로 표시합니다. API 참고 금액입니다.','모델 단가 보기','백만 token당 실제 적용 요금과 컨텍스트 구간입니다. —는 해당 단가가 없음을 뜻합니다.','적용 가능한 단가 없음','캐시 쓰기 · 5분','캐시 쓰기 · 1시간','입력 컨텍스트 ≥ {count} token','전체 token 합계가 제공되지 않음','일부 과거 상세 기록이 만료되었습니다. 참고 금액은 보존된 기록만 포함합니다.','할당량 상세'],
  es:['Tarifas actuales disponibles por moneda; solo referencia de API.','Ver precios unitarios','Por millón de tokens; tarifas aplicadas y tramos de contexto. — indica una tarifa ausente.','Sin precio unitario aplicable','Escritura de caché · 5 min','Escritura de caché · 1 hora','Contexto de entrada ≥ {count} tokens','No se proporcionó el total completo de tokens','Algunos detalles históricos han caducado; los importes solo cubren los conservados.','Detalles de cuota'],
  fr:['Tarifs disponibles actuels par devise ; référence API uniquement.','Voir les prix unitaires','Par million de tokens ; tarifs appliqués et seuils de contexte. — indique un tarif absent.','Aucun prix unitaire applicable','Écriture cache · 5 min','Écriture cache · 1 heure','Contexte d’entrée ≥ {count} tokens','Total complet de tokens non fourni','Certains détails historiques ont expiré ; seuls les détails conservés sont couverts.','Détails du quota'],
  de:['Aktuell verfügbare Tarife je Währung; nur API-Referenz.','Modellpreise ansehen','Je Million Tokens; angewandte Preise und Kontextstufen. — bedeutet kein Preis für diesen Anteil.','Kein anwendbarer Einzelpreis','Cache-Schreiben · 5 Min.','Cache-Schreiben · 1 Std.','Eingabekontext ≥ {count} Tokens','Vollständige Token-Summe nicht angegeben','Einige historische Details sind abgelaufen; Beträge umfassen nur aufbewahrte Details.','Kontingentdetails'],
  'pt-BR':['Tarifas atuais disponíveis por moeda; apenas referência de API.','Ver preços unitários','Por milhão de tokens; tarifas aplicadas e faixas de contexto. — indica uma tarifa ausente.','Sem preço unitário aplicável','Gravação de cache · 5 min','Gravação de cache · 1 hora','Contexto de entrada ≥ {count} tokens','Total completo de tokens não informado','Alguns detalhes históricos expiraram; os valores cobrem apenas os registros preservados.','Detalhes da cota'],
  ru:['Текущие доступные тарифы по валютам; только справочная оценка API.','Посмотреть цены моделей','За миллион токенов; применённые тарифы и пороги контекста. — означает отсутствие тарифа.','Подходящего тарифа нет','Запись кэша · 5 мин','Запись кэша · 1 час','Входной контекст ≥ {count} токенов','Полное число токенов не предоставлено','Некоторые исторические записи удалены по сроку хранения; оценка охватывает только сохранённые записи.','Подробности квоты'],
};
const titles:Record<string,string>={'zh-CN':'API按量付费价格参考','zh-TW':'API 按量付費價格參考',en:'API pay-as-you-go price reference',ja:'API 従量課金の参考額',ko:'API 종량제 가격 참고',es:'Referencia de precios API por uso',fr:'Référence des tarifs API à l’usage',de:'API-Preisreferenz nach Verbrauch','pt-BR':'Referência de preços API por uso',ru:'Справочная стоимость API по использованию'};
export const referenceCatalogs=Object.fromEntries(Object.entries(phrases).map(([locale,values])=>{
  if(values.length!==keys.length) throw new Error('Incomplete reference translations: '+locale);
  return [locale,{...Object.fromEntries(keys.map((key,index)=>[key,values[index]])),
    'cost.currentSim':titles[locale],'cost.title':titles[locale],'dashboard.modelCost':titles[locale],
    'dashboard.costCurveHint':values[0],'chart.unknownTotals':`${values[7]}: {names}`}];
}));
