const keys = ['title','schedule','schedule.launch','schedule.daily','schedule.weekly','schedule.manual','autoDownload','settingsHint','current','lastCheck','kind.portable','kind.installer','kind.unknown','unknownHint','progress','error','check','download','install','restart','cancel','dismiss','restartHint','phase.idle','phase.checking','phase.up_to_date','phase.available','phase.downloading','phase.verifying','phase.ready','phase.installing','phase.cancelled','phase.error'];
const phrases: Record<string, string[]> = {
  'zh-CN': ['软件更新','检查频率','每次启动','每天一次','每周一次','仅手动检查','发现新版本后自动下载','保存后生效。仅在软件运行时检查更新，不发送本机用量数据；下载完成后仍需手动确认更新。','当前版本：{version}','上次检查：{time}','便携版','安装版','安装类型未知','请使用官方安装包或完整解压的便携版，以便下载对应类型的更新。','更新下载进度','更新失败：{message}','检查更新','下载更新','安装更新','重启并更新','取消','关闭通知','更新时会关闭并重新启动软件，保留用量数据、设置和原有路径。','尚未检查更新','正在检查更新…','已是最新版本','发现新版本 {version}','正在下载 {version}…','正在校验并准备更新…','{version} 已下载，可以安装更新','正在安装更新…','已取消更新','更新未完成'],
  'zh-TW': ['軟體更新','檢查頻率','每次啟動','每天一次','每週一次','僅手動檢查','發現新版本後自動下載','儲存後生效。僅在軟體執行時檢查更新，不傳送本機用量資料；下載完成後仍須手動確認更新。','目前版本：{version}','上次檢查：{time}','可攜版','安裝版','安裝類型不明','請使用官方安裝程式或完整解壓縮的可攜版，以便下載對應類型的更新。','更新下載進度','更新失敗：{message}','檢查更新','下載更新','安裝更新','重新啟動並更新','取消','關閉通知','更新時會關閉並重新啟動軟體，保留用量資料、設定及原有路徑。','尚未檢查更新','正在檢查更新…','已是最新版本','發現新版本 {version}','正在下載 {version}…','正在驗證並準備更新…','{version} 已下載，可以安裝更新','正在安裝更新…','已取消更新','更新未完成'],
  en: ['Software updates','Check frequency','Every launch','Once a day','Once a week','Manual checks only','Automatically download new versions','Changes take effect after saving. Updates are checked only while the app is running, without sending local usage data. Installing an update still requires your confirmation.','Current version: {version}','Last check: {time}','Portable version','Installed version','Unknown package type','Use the official installer or a fully extracted portable version to download the matching update.','Update download progress','Update failed: {message}','Check for updates','Download update','Install update','Restart and update','Cancel','Dismiss notification','Updating closes and restarts the app. Usage data, settings and existing paths are preserved.','Updates have not been checked','Checking for updates…','LLM Usage is up to date','Version {version} is available','Downloading {version}…','Verifying and preparing update…','{version} is downloaded and ready to install','Installing update…','Update cancelled','Update did not complete'],
  ja: ['ソフトウェアの更新','確認頻度','起動するたび','1日1回','週1回','手動のみ','新しいバージョンを自動ダウンロード','変更は保存後に反映されます。アプリの実行中のみ更新を確認し、ローカルの使用量データは送信しません。更新のインストールには確認が必要です。','現在のバージョン：{version}','前回の確認：{time}','ポータブル版','インストール版','パッケージ形式不明','公式インストーラーまたは完全に展開したポータブル版を使用してください。','更新のダウンロード進捗','更新失敗：{message}','更新を確認','更新をダウンロード','更新をインストール','再起動して更新','キャンセル','通知を閉じる','更新時にアプリを閉じて再起動します。使用量、設定、パスは保持されます。','まだ更新を確認していません','更新を確認中…','LLM Usage は最新バージョンです','バージョン {version} が利用できます','{version} をダウンロード中…','更新を検証して準備中…','{version} のダウンロードが完了しました','更新をインストール中…','更新をキャンセルしました','更新が完了しませんでした'],
  ko: ['앱 업데이트','확인 주기','앱을 시작할 때마다','하루 한 번','주 한 번','수동 확인만','새 버전 자동 다운로드','변경 사항은 저장 후 적용됩니다. 앱 실행 중에만 업데이트를 확인하며 로컬 사용량 데이터를 전송하지 않습니다. 업데이트를 설치하려면 사용자의 확인이 필요합니다.','현재 버전: {version}','마지막 확인: {time}','포터블 버전','설치 버전','알 수 없는 패키지 유형','공식 설치 파일 또는 완전히 압축을 푼 포터블 패키지를 사용하세요.','업데이트 다운로드 진행률','업데이트 실패: {message}','업데이트 확인','업데이트 다운로드','업데이트 설치','다시 시작하여 업데이트','취소','알림 닫기','업데이트 시 앱을 닫고 다시 엽니다. 사용량, 설정 및 경로는 유지됩니다.','업데이트를 확인하지 않았습니다','업데이트 확인 중…','LLM Usage가 최신 버전입니다','새 버전 {version}을 사용할 수 있습니다','{version} 다운로드 중…','업데이트 검증 및 준비 중…','{version} 다운로드 완료','업데이트 설치 중…','업데이트가 취소되었습니다','업데이트가 완료되지 않았습니다'],
  es: ['Actualizaciones','Frecuencia de comprobación','En cada inicio','Una vez al día','Una vez por semana','Solo manual','Descargar nuevas versiones automáticamente','Los cambios se aplican al guardar. Solo se buscan actualizaciones mientras la aplicación está abierta, sin enviar datos de uso locales. La instalación requiere tu confirmación.','Versión actual: {version}','Última comprobación: {time}','Versión portátil','Versión instalada','Tipo de paquete desconocido','Usa el instalador oficial o una versión portátil completamente extraída para descargar la actualización correspondiente.','Progreso de descarga','Error de actualización: {message}','Buscar actualizaciones','Descargar actualización','Instalar actualización','Reiniciar y actualizar','Cancelar','Cerrar notificación','La aplicación se cierra y se reinicia al actualizar. Se conservan los datos de uso, los ajustes y las rutas.','No se han buscado actualizaciones','Buscando actualizaciones…','LLM Usage está actualizado','Versión {version} disponible','Descargando {version}…','Verificando y preparando…','La versión {version} se ha descargado y está lista para instalar','Instalando actualización…','Actualización cancelada','La actualización no se completó'],
  fr: ['Mises à jour','Fréquence de vérification','À chaque lancement','Une fois par jour','Une fois par semaine','Manuellement','Télécharger automatiquement les nouvelles versions','Les modifications prennent effet après l’enregistrement. La recherche de mises à jour se fait uniquement lorsque l’application est ouverte, sans envoi de données d’usage locales. L’installation nécessite votre confirmation.','Version actuelle : {version}','Dernière vérification : {time}','Version portable','Version installée','Type de paquet inconnu','Utilisez le programme d’installation officiel ou une version portable entièrement extraite pour télécharger la mise à jour correspondante.','Progression du téléchargement','Échec de la mise à jour : {message}','Rechercher des mises à jour','Télécharger la mise à jour','Installer la mise à jour','Redémarrer et mettre à jour','Annuler','Fermer la notification','L’application se ferme et redémarre lors de la mise à jour. Les données d’usage, les paramètres et les chemins sont conservés.','Aucune vérification effectuée','Recherche de mises à jour…','LLM Usage est à jour','Version {version} disponible','Téléchargement de {version}…','Vérification et préparation…','La version {version} est téléchargée et prête à être installée','Installation de la mise à jour…','Mise à jour annulée','La mise à jour n’a pas abouti'],
  de: ['Updates','Prüfintervall','Bei jedem Start','Einmal täglich','Einmal wöchentlich','Nur manuell','Neue Versionen automatisch herunterladen','Änderungen werden nach dem Speichern wirksam. Updates werden nur bei laufender App geprüft; lokale Nutzungsdaten werden nicht gesendet. Die Installation muss bestätigt werden.','Aktuelle Version: {version}','Letzte Prüfung: {time}','Portable-Version','Installierte Version','Unbekannter Pakettyp','Das offizielle Installationsprogramm oder eine vollständig entpackte Portable-Version verwenden, um das passende Update herunterzuladen.','Downloadfortschritt','Update fehlgeschlagen: {message}','Nach Updates suchen','Update herunterladen','Update installieren','Neu starten und aktualisieren','Abbrechen','Benachrichtigung schließen','Die App wird beim Aktualisieren geschlossen und neu gestartet. Nutzungsdaten, Einstellungen und Pfade bleiben erhalten.','Noch nicht geprüft','Updates werden gesucht…','LLM Usage ist aktuell','Version {version} verfügbar','{version} wird heruntergeladen…','Update wird geprüft und vorbereitet…','{version} wurde heruntergeladen und kann installiert werden','Update wird installiert…','Update abgebrochen','Update nicht abgeschlossen'],
  'pt-BR': ['Atualizações','Frequência de verificação','A cada abertura','Uma vez por dia','Uma vez por semana','Somente manual','Baixar novas versões automaticamente','As alterações entram em vigor após salvar. As atualizações são verificadas apenas enquanto o aplicativo está aberto, sem enviar dados de uso locais. A instalação exige sua confirmação.','Versão atual: {version}','Última verificação: {time}','Versão portátil','Versão instalada','Tipo de pacote desconhecido','Use o instalador oficial ou uma versão portátil totalmente extraída para baixar a atualização correspondente.','Progresso do download','Falha na atualização: {message}','Verificar se há atualizações','Baixar atualização','Instalar atualização','Reiniciar e atualizar','Cancelar','Fechar notificação','O aplicativo fecha e reinicia durante a atualização. Os dados de uso, as configurações e os caminhos são preservados.','Atualizações ainda não verificadas','Verificando se há atualizações…','O LLM Usage está atualizado','Versão {version} disponível','Baixando {version}…','Verificando e preparando…','A versão {version} foi baixada e está pronta para instalar','Instalando atualização…','Atualização cancelada','A atualização não foi concluída'],
  ru: ['Обновления приложения','Частота проверки','При каждом запуске','Раз в день','Раз в неделю','Только вручную','Автоматически загружать новые версии','Изменения вступают в силу после сохранения. Проверка обновлений выполняется только при запущенном приложении без отправки локальных данных об использовании. Для установки требуется ваше подтверждение.','Текущая версия: {version}','Последняя проверка: {time}','Переносная версия','Установленная версия','Неизвестный тип пакета','Используйте официальный установщик или полностью распакованную переносную версию, чтобы загрузить подходящее обновление.','Ход загрузки обновления','Ошибка обновления: {message}','Проверить наличие обновлений','Загрузить обновление','Установить обновление','Перезапустить и обновить','Отмена','Закрыть уведомление','Приложение закроется и откроется снова. Данные, настройки и пути сохранятся.','Обновления ещё не проверялись','Проверка наличия обновлений…','Установлена последняя версия','Доступна версия {version}','Загрузка {version}…','Проверка и подготовка обновления…','Версия {version} загружена и готова к установке','Установка обновления…','Обновление отменено','Обновление не завершено'],
};
const development: Record<string, [string, string]> = {
  'zh-CN': ['开发模式', '开发模式可以检查新版本。下载和安装更新请使用官方安装版或完整解压的便携版。'],
  'zh-TW': ['開發模式', '開發模式可以檢查新版本。下載及安裝更新請使用官方安裝版或完整解壓縮的可攜版。'],
  en: ['Development mode', 'Development mode can check for new versions. Use the official installed or fully extracted portable version to download and install updates.'],
  ja: ['開発モード', '開発モードでは新しいバージョンを確認できます。更新のダウンロードとインストールには、公式のインストール版または完全に展開したポータブル版を使用してください。'],
  ko: ['개발 모드', '개발 모드에서 새 버전을 확인할 수 있습니다. 업데이트를 다운로드하고 설치하려면 공식 설치 버전 또는 압축을 완전히 푼 포터블 버전을 사용하세요.'],
  es: ['Modo de desarrollo', 'El modo de desarrollo permite buscar nuevas versiones. Para descargar e instalar actualizaciones, use la versión oficial instalada o portátil completamente extraída.'],
  fr: ['Mode développement', 'Le mode développement permet de rechercher de nouvelles versions. Pour télécharger et installer les mises à jour, utilisez la version officielle installée ou portable entièrement extraite.'],
  de: ['Entwicklungsmodus', 'Im Entwicklungsmodus lassen sich neue Versionen prüfen. Zum Herunterladen und Installieren von Updates die offiziell installierte oder vollständig entpackte Portable-Version verwenden.'],
  'pt-BR': ['Modo de desenvolvimento', 'O modo de desenvolvimento permite verificar novas versões. Para baixar e instalar atualizações, use a versão oficial instalada ou portátil totalmente extraída.'],
  ru: ['Режим разработки', 'В режиме разработки можно проверять наличие новых версий. Для загрузки и установки обновлений используйте официальную установленную или полностью распакованную переносную версию.'],
};
export const updateCatalogs = Object.fromEntries(Object.entries(phrases).map(([locale, values]) => {
  if (values.length !== keys.length) throw new Error(`Incomplete update translations: ${locale}`);
  return [locale, {...Object.fromEntries(keys.map((key, index) => [`updates.${key}`, values[index]])), 'updates.kind.development': development[locale][0], 'updates.developmentHint': development[locale][1]}];
})) as Record<string, Record<string, string>>;
